server:
  servlet:
    context-path: /dome

mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:com/example/dao/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

#thymeleaf start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#thymeleaf end

#pagehelper
pagehelper:
  auto-dialect: mysql
  reasonable: true
  page-size-zero: true
